### ISSUE TITLE
`window is not defined` with SSR

### ISSUE THREAD

**Issue by nsmdnl** [stufreen/animol#2]
Hey there! 👋🏼
I tried animating elements in my Next.js application, but unfortunately I get the error `ReferenceError: window is not defined`. Looks like this is a problem with server-side rendering where `window` is not available, but referred to by animol. 😄

**Comment by stufreen** [comment]
Thanks @nsmdnl ! Should be fixed now in v 1.0.10.

If supporting old browsers isn't a concern you might also check out the Element.Animate API: https://developer.mozilla.org/en-US/docs/Web/API/Element/animate

**Comment by nsmdnl** [comment]
Hey @stufreen, thanks for your answer! 

Unfortunately the issue is still there. I had a similar issue in my package, but what fixed it was putting the whole code in the condition `if (typeof window !== "undefined")` ([Here's an explanation](https://flaviocopes.com/nextjs-server-client-code/) and [this is my use case](https://github.com/nsmdnl/css-container-queries/blob/5f14bcca0a89a4d0522c787bc2033a11ae4dcb78/src/css-cq.js#L1)). I modified animol's code locally in my project to test this, an it seemed to fix the issue.

I hope this can help!

**Comment by stufreen** [comment]
That was basically what I did - looks like Webpack needed a configuration change. I just pushed a new version 1.0.11 that should fix it for you (just tested with barebones Next app). Thanks again!
